# Generated by Django 5.1.2 on 2024-11-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('pdetails', models.CharField(max_length=100)),
                ('cat', models.IntegerField(choices=[(1, 'Mobile'), (2, 'cloths'), (3, 'shoes')], verbose_name='Product Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Availabel')),
            ],
        ),
    ]
